Build wheel for mysqlclient on MacOS
ipwhl/cheese-maker pull request #22
Opened 2021-10-27 15:45 UTC by 9a24f0

2021-10-28 02:38 UTC, Huy-Ngo requested changes

2021-10-28 02:38 UTC, Huy-Ngo commented on .github/workflows/build.yml
> +          CIBW_BEFORE_ALL_MACOS: export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
```suggestion
          CIBW_BEFORE_ALL_MACOS: |
            brew install mysql gcc openssl@1.1
            export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
```
Why not use [newer version](https://formulae.brew.sh/formula/openssl@3#default) though? Also I still don't think this is correct. I don't use mac but usually installation command install binaries/libs on /usr/bin and /usr/lib, not /usr/local/opt

2021-10-29 12:13 UTC, Huy-Ngo commented
>   Warning: gcc 11.2.0 is already installed and up-to-date.
  To reinstall 11.2.0, run:
    brew reinstall gcc
  Warning: openssl@1.1 1.1.1l_1 is already installed and up-to-date.


So, openssl is already installed.

I recommend you follow the official instruction.

2021-10-29 13:06 UTC, Huy-Ngo commented
> I recommend you follow the official instruction.

Nvm that, I don't think that work.

Maybe can you try these https://stackoverflow.com/questions/33362853/os-x-cannot-find-ssl-headers?

2021-10-29 17:00 UTC, Huy-Ngo commented
> Warning: Refusing to link macOS provided/shadowed software: openssl@1.1
  If you need to have openssl@1.1 first in your PATH, run:
    echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> /Users/runner/.bash_profile
  
  > For compilers to find openssl@1.1 you may need to set:
    export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
    export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
  
 I suppose setting LDFLAGS should help.

2021-10-29 17:07 UTC, 9a24f0 commented
> > Warning: Refusing to link macOS provided/shadowed software: openssl@1.1
> > If you need to have openssl@1.1 first in your PATH, run:
> > echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> /Users/runner/.bash_profile
> 
> > For compilers to find openssl@1.1 you may need to set:
> > export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
> > export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
> 
> I suppose setting LDFLAGS should help.

Seemingly not LOL

2021-10-30 01:54 UTC, Huy-Ngo commented
I hope someone who use and know Mac can help :D

2021-10-30 06:47 UTC, Huy-Ngo approved these changes

2021-10-30 06:48 UTC, Huy-Ngo commented
Nice, thank you.

> We went looking everywhere, but couldn’t find those commits.

You don't have to squash the commits and force-push.

2021-10-30 06:49 UTC, merged

2021-10-30 07:14 UTC, Huy-Ngo commented
Oh right, should have checked [the doc](https://cibuildwheel.readthedocs.io/en/stable/options/#environment) first :sweat_smile: